[package]
name = "tinyrender"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
tgaimage = "0.1.1"

[profile.release]
debug = 1

[rust]
debuginfo-level = 1

[build]
rustflags = ["-C", "symbol-mangling-version=v0"]
